import type { Metadata } from "next";
import { Inter, Playfair_Display, Geist, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReduxProvider from "../provider/ReduxProvider";
import { Toaster } from "sonner";

// const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-poppins",
});

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   variable: "--font-serif",
// });

export const metadata: Metadata = {
  title: "KidsHut BD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", poppins.variable)}>
      <body className="min-h-full flex flex-col ">
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
